Models/CustomerModel.cs
using System.ComponentModel.DataAnnotations;

namespace WebApplication1.Models
{
    public class CustomerModel
    {
        [Key] 
        public int cus_id { get; set; }
        public string cus_name { get; set; }
        public string cus_lname { get; set; }
        public string cus_add { get; set; }
        public string cus_tel { get; set; }
        public DateTime bdate { get; set; }
        public string sex { get; set; }
        public string username { get; set; }
        public string password { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace WebApplication1.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/TypeProduct.cs
using System.ComponentModel.DataAnnotations;

namespace WebApplication1.Models
{
    public class TypeProduct
    {
        [Key] //4.set type_id Prymary key
        public int type_id { get; set; } 
        public string type_name { get; set; }
    }
}

Controllers/CustomerController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Data;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class CustomerController : Controller
    {
        private readonly CustomerContext _contextCus;

        public CustomerController(CustomerContext context)
        {
            _contextCus = context; 
        }
        public async Task<IActionResult> Index()
        {
            var customers = await _contextCus.tb_customer.ToListAsync();
            return View(customers);
        }
        public ActionResult Create() { 
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CustomerModel cus)
        {

            if (ModelState.IsValid)
            {
                _contextCus.tb_customer.Add(cus);
                await _contextCus.SaveChangesAsync();  
                //TempData["SuccessMessage"] = "Customer add success";
                return RedirectToAction("Index"); 
            }
            else
            {
                //TempData["ErrorMessage"] = "Error: Unable to add the product. Please try again.";  // Set error message
                return View(cus);
            }

        }

        [HttpGet]
        public async Task<IActionResult> Detail(int? id)
        {
            if (id == null || id <= 0) return BadRequest();
            var cus = await _contextCus.tb_customer.FirstOrDefaultAsync(c => c.cus_id == id);
            if (cus == null) return NotFound();
            return View(cus);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id <= 0) return BadRequest();

            var del = await _contextCus.tb_customer.FirstOrDefaultAsync(t => t.cus_id == id);
            if (del == null) return NotFound();

            _contextCus.tb_customer.Remove(del);
            await _contextCus.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id) //id มาจากหน้า index TypeProduct
        {
            if (id == null || id <= 0) return BadRequest();
            var customer = await _contextCus.tb_customer.FirstOrDefaultAsync(c => c.cus_id == id);
            //when found data return data by id
            if (customer == null) return NotFound();
            return View(customer);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, CustomerModel customer)
        {
            var cus = await _contextCus.tb_customer.FirstOrDefaultAsync(t => t.cus_id == id);
            if (cus == null) return NotFound();
            cus.cus_name = customer.cus_name;
            cus.cus_lname = customer.cus_lname;
            cus.cus_add = customer.cus_add;
            cus.cus_tel = customer.cus_tel;
            cus.bdate = customer.bdate;
            cus.sex = customer.sex;
            cus.username = customer.username;
            cus.password = customer.password;
            await _contextCus.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/TypeProductController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Data;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{

    public class TypeProductController : Controller
    {
        private readonly TypeProductContext _context;

        public TypeProductController(TypeProductContext context) { 

            _context = context; //connect to db
        }
        public async Task<IActionResult>Index()
        {
            var typeproduct = await _context.ProductType.ToListAsync();
            return View(typeproduct); //add view right at View(); / add view 
        }

        [HttpPost]
        public async Task<IActionResult> Create(TypeProduct tproduct) {

            if (ModelState.IsValid)
            {
                _context.ProductType.Add(tproduct);
                await _context.SaveChangesAsync();  //save to db
                TempData["SuccessMessage"] = "Type product add success";
                return RedirectToAction("Index");   //go to main page main when add success
            }
            else { 
                //TempData["ErrorMessage"] = "Error: Unable to add the product. Please try again.";  // Set error message
                return View(tproduct);
            }

        }
        [HttpGet]
        public async Task<IActionResult> Edit(int? id) //id มาจากหน้า index TypeProduct
        {
            if (id == null || id <= 0) return BadRequest();
            var typeproduct = await _context.ProductType.FirstOrDefaultAsync(c => c.type_id == id);
            //when found data return data by id
            if(typeproduct == null) return NotFound();
            return View(typeproduct);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, TypeProduct typeproduct) {
            var type = await _context.ProductType.FirstOrDefaultAsync(t => t.type_id == id);
            if (type == null) return NotFound();
            type.type_name = typeproduct.type_name; 
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Delete(int? id)
        {
            if (id <= 0) return BadRequest();

            var del = await _context.ProductType.FirstOrDefaultAsync(t => t.type_id == id);
            if (del == null) return NotFound();

            _context.ProductType.Remove(del);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }
        [HttpGet]
        public async Task<IActionResult> Detail(int? id) //id มาจากหน้า index TypeProduct
        {
            if (id == null || id <= 0) return BadRequest();
            var typeproduct = await _context.ProductType.FirstOrDefaultAsync(c => c.type_id == id);
            //when found data return data by id
            if (typeproduct == null) return NotFound();
            return View(typeproduct);
        }
    }
}

Views/Customer/Create.cshtml
@model WebApplication1.Models.CustomerModel
@section Scripts {
        <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
        <script>

        @if (TempData["SuccessMessage"] != null)
        {
            <text>
                        Swal.fire({
                            icon: 'success',
                            title: 'Success',
                            text: '@TempData["SuccessMessage"]'
                        });
            </text>
        }

        @if (TempData["ErrorMessage"] != null)
        {
            <text>
                        Swal.fire({
                            icon: 'error',
                            title: 'Error',
                            text: '@TempData["ErrorMessage"]'
                        });
            </text>
        }
        </script>
}



<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form asp-action="Create" class="border p-4 shadow-sm rounded">
                <div class="form-group">
                    <label for="cus_name" class="form-label">ชื่อ</label>
                    <input asp-for="cus_name" class="form-control" id="cus_name" type="name" placeholder="กรุณากรอกชื่อ" require/>
                    <br/>
                    <label for="cus_lname" class="form-label">นามสกุล</label>
                    <input asp-for="cus_lname" class="form-control" id="cus_lname" type="name" placeholder="กรุณากรอกนามสกุล" require/>
                    <br/>
                    <label for="cus_add" class="form-label">ที่อยู่</label>
                    <input asp-for="cus_add" class="form-control" id="cus_add" type="name" placeholder="กรุณากรอกที่อยู่" require/>
                    <br/>
                    <label asp-for="bdate" for="bdate" class="form-label">วันเกิด</label>
                    <input class="form-control" asp-for="bdate" type="date" required />
                    <br/>
                    <label for="tel" class="form-label">เบอร์โทร</label>
                    <input asp-for="cus_tel" class="form-control" type="name" id="cus_tel" placeholder="กรุณากรอกเบอร์โทร" require/>
                    <br/>
                    <label for="sex" class="form-label">เพศ</label>
                        <select asp-for="sex" class="form-control" id="sex" required>
                            <option value="" disabled selected>กรุณาเลือกเพศ</option>
                            <option value="male">ชาย</option>
                            <option value="female">หญิง</option>
                        </select>
                    <br />
                    <label for="username" class="form-label">Username</label>
                    <input asp-for="username" class="form-control" id="username" type="name" placeholder="กรุณากรอก Username" require/>
                    <br/>
                    <label for="password" class="form-label">password</label>
                    <input asp-for="password" class="form-control" id="password" type="password" placeholder="กรุณากรอก password" require/>
                    <br/>
                </div>
                <div class="form-group mt-3">
                    <input type="submit" value="Create" class="btn btn-success btn-block" />
                </div>
            </form>
        </div>
    </div>
</div>

Views/Customer/Detail.cshtml
@model WebApplication1.Models.CustomerModel

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="border p-4 shadow-sm rounded">
                <!-- ตาราง responsive -->
                <div class="table-responsive">
                    <table class="table table-bordered table-striped table-hover mt-3">
                        <thead class="thead-light">
                            <tr>
                                <th>รหัสลูกค้า</th>
                                <th>ชื่อ</th>
                                <th>นามสกุล</th>
                                <th>ที่อยู่</th>
                                <th>วันเกิด</th>
                                <th>เพศ</th>
                                <th>Username</th>
                                <th>Password</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>@Html.DisplayFor(t => t.cus_id)</td>
                                <td>@Html.DisplayFor(t => t.cus_name)</td>
                                <td>@Html.DisplayFor(t => t.cus_lname)</td>
                                <td>@Html.DisplayFor(t => t.cus_add)</td>
                                <td>@Html.DisplayFor(t => t.bdate)</td>
                                <td>@Html.DisplayFor(t => t.sex)</td>
                                <td>@Html.DisplayFor(t => t.username)</td>
                                <td>@Html.DisplayFor(t => t.password)</td>
                            </tr>
                        </tbody>
                    </table>
                </div>

                <div class="form-group mt-3">
                    <a asp-action="Index" class="btn btn-primary btn-block">กลับไปยังหน้าแรก</a>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Customer/Edit.cshtml
@model WebApplication1.Models.CustomerModel //get str in textfield


<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form asp-action="Edit" class="border p-4 shadow-sm rounded">
                <div class="form-group">
                    <label for="type_name" class="form-label">ชื่อ</label>
                    <input asp-for="cus_name" class="form-control" id="cus_name" type="name" placeholder="กรุณากรอกชื่อที่ต้องการแก้ไข" />
                    <br/>
                    <label for="type_name" class="form-label">นามสกุล</label>
                    <input asp-for="cus_lname" class="form-control" id="cus_lname" type="name" placeholder="กรุณากรอกนามสกุลที่ต้องการแก้ไข" />
                    <br/>
                    <label for="type_name" class="form-label">ที่อยู่</label>
                    <input asp-for="cus_add" class="form-control" id="cus_add" type="name" placeholder="กรุณากรอกที่อยู่ที่ต้องการแก้ไข" />
                    <br/>
                    <label for="type_name" class="form-label">เบอร์โทร</label>
                    <input asp-for="cus_tel" class="form-control" id="cus_tel" type="name" placeholder="กรุณากรอกเบอร์โทรที่ต้องการแก้ไข" />
                    <br/>
                    <label for="type_name" class="form-label">วันเกิด</label>
                    <input asp-for="bdate" class="form-control" id="bdate" type="date" placeholder="กรุณากรอกวันเกิดที่ต้องการแก้ไข" />
                    <br/>
                    <label for="sex" class="form-label">เพศ</label>
                        <select asp-for="sex" class="form-control" id="sex" required>
                            <option value="" disabled selected>กรุณาเลือกเพศ</option>
                            <option value="male">ชาย</option>
                            <option value="female">หญิง</option>
                        </select>
                    <br />
                    <label for="type_name" class="form-label">Username</label>
                    <input asp-for="username" class="form-control" id="username" type="name" placeholder="กรุณากรอก Username ที่ต้องการแก้ไข" />
                    <br/>
                    <label for="type_name" class="form-label">Password</label>
                    <input asp-for="password" class="form-control" id="password" type="name" placeholder="กรุณากรอก Password ที่ต้องการแก้ไข" />
                    <br/>
                </div>
                <div class="form-group mt-3">
                    <a asp-action="Index" class="btn btn-primary btn-block">กลับไปยังหน้าแรก</a>
                    <input type="submit" value="แก้ไขข้อมูล" class="btn btn-success btn-block"/>
                </div>
            </form>
        </div>
    </div>
</div>

Views/Customer/index.cshtml
@model IEnumerable<WebApplication1.Models.CustomerModel>  

<div>
    <div class="pb-2">
        <form asp-controller="Customer" asp-action="Create" method="post">
            <button type="submit" class="btn btn-success">เพิ่มข้อมูลลูกค้า</button>
        </form>
    </div>
    <table class="table table-striped table-bordered">
        <thead class="thead-dark">
            <tr>
                <th>รหัสลูกค้า</th>
                <th>ชื่อ</th>
                <th>นามสกุล</th>
                <th>ที่อยู่</th>
                <th>วันเกิด</th>
                <th>เพศ</th>
                <th>Username</th>
                <th>Password</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                    <tr>
                        <td>@Html.DisplayFor(t => item.cus_id)</td>
                        <td>@Html.DisplayFor(t => item.cus_name)</td>
                        <td>@Html.DisplayFor(t => item.cus_lname)</td>
                        <td>@Html.DisplayFor(t => item.cus_add)</td>
                        <td>@Html.DisplayFor(t => item.bdate)</td>
                        <td>@Html.DisplayFor(t => item.sex)</td>
                        <td>@Html.DisplayFor(t => item.username)</td>
                        <td>@Html.DisplayFor(t => item.password)</td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", new { id = item.cus_id }, new { @class = "btn btn-primary btn-sm" })  |
                            @Html.ActionLink("Delete", "Delete", new { id = item.cus_id }, new { @class = "btn btn-danger btn-sm", onclick = "return confirm('ต้องการลบหรือไม่?');" })|
                            @Html.ActionLink("Detail", "Detail", new { id = item.cus_id }, new { @class = "btn btn-info btn-sm" })
                        </td>
                    </tr>
            }
        </tbody>
    </table>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2567 - WebApplication1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/TypeProduct/Create.cshtml
@model WebApplication1.Models.TypeProduct //get str in textfield
@section Scripts {
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script>
        @if (TempData["SuccessMessage"] != null)
        {
            <text>
                Swal.fire({
                    icon: 'success',
                    title: 'Success',
                    text: '@TempData["SuccessMessage"]'
                });
            </text>
        }

        @if (TempData["ErrorMessage"] != null)
        {
            <text>
                Swal.fire({
                    icon: 'error',
                    title: 'Error',
                    text: '@TempData["ErrorMessage"]'
                });
            </text>
        }
    </script>
}


<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form asp-action="Create" class="border p-4 shadow-sm rounded">
                <div class="form-group">
                    <label for="type_name" class="form-label">ชื่อรหัสสินค้า</label>
                    <input asp-for="type_name" class="form-control" id="type_name" type="name" placeholder="กรุณากรอกชื่อรหัสสินค้า" />
                </div>
                <div class="form-group mt-3">
                    <input type="submit" value="Create" class="btn btn-primary btn-block" />
                </div>
            </form>
        </div>
    </div>
</div>

Views/TypeProduct/Detail.cshtml
@model WebApplication1.Models.TypeProduct

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="border p-4 shadow-sm rounded">
                <table class="table table-bordered table-striped table-hover mt-3">
                    <thead class="thead-light">
                        <tr>
                            <th>รหัสประเภทสินค้า</th>
                            <th>ชื่อประเภทสินค้า</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>@Html.DisplayFor(t => t.type_id)</td>
                            <td>@Html.DisplayFor(t => t.type_name)</td>
                        </tr>
                    </tbody>
                </table>

                <div class="form-group mt-3">
                    <a asp-action="Index" class="btn btn-primary btn-block">กลับไปยังหน้าแรก</a>
                </div>
            </div>
        </div>
    </div>
</div>

Views/TypeProduct/Edit.cshtml
@model WebApplication1.Models.TypeProduct //get str in textfield


<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form asp-action="Edit" class="border p-4 shadow-sm rounded">
                <div class="form-group">
                    <label for="type_name" class="form-label">ชื่อสินค้า</label>
                    <input asp-for="type_name" class="form-control" id="type_name" type="name" placeholder="กรุณากรอกชื่อที่ต้องการแก้ไข" />
                </div>
                <div class="form-group mt-3">
                    <a asp-action="Index" class="btn btn-primary btn-block">กลับไปยังหน้าแรก</a>
                    <input type="submit" value="Edit" class="btn btn-primary btn-block" />
                </div>
            </form>
        </div>
    </div>
</div>

Views/TypeProduct/Index.cshtml
@model IEnumerable<WebApplication1.Models.TypeProduct>  //get TypeProduct from model json to str to display

<div>
    <div class="pb-2">
        <form asp-controller="TypeProduct" asp-action="Create" method="post">
            <button type="submit" class="btn btn-success">Create Type Product</button>
        </form>
    </div>
    <table class="table table-striped table-bordered">
        <thead class="thead-dark">
            <tr>
                <th>รหัสประเภทสินค้า</th>
                <th>ชื่อประเภทสินค้า</th>
                <th>ลิงค์</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(t => item.type_id)</td>
                    <td>@Html.DisplayFor(t => item.type_name)</td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.type_id }, new { @class = "btn btn-primary btn-sm" })  |
                        @Html.ActionLink("Delete", "Delete", new { id = item.type_id }, new { @class = "btn btn-danger btn-sm", onclick = "return confirm('ต้องการลบหรือไม่?');" })|
                        @Html.ActionLink("Detail", "Detail", new { id = item.type_id }, new { @class = "btn btn-info btn-sm" })
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>